version: '3'

services:
  web:
    image: myflix3:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Myflixproject.settings.prod  # Adjust the path accordingly
    volumes:
      - /Myflix3/netclone/Myflix/Myflixproject/static/assets/media:/assets/media
      - /Myflix3/netclone/Myflix/Myflixproject/static:/Myflixproject/static
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
